version: '3.4'

networks:
    liveplay-net:
        driver: bridge

services:
    liveplay.server.webapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=5094
            - ASPNETCORE_HTTPS_PORTS=7001
        container_name: liveplay.server.webapi
        image: ${DOCKER_REGISTRY-}liveplayserverwebapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5094:5094"
            - "7001:7001"
        networks:
            - liveplay-net
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        depends_on:
            - postgres_db

    postgres_db:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Qwertyuiop123
            POSTGRES_DB: LivePlay
        ports:
            - 5432:5432
        networks:
            - liveplay-net
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
