// <auto-generated />
using System;
using LivePlay.Server.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LivePlay.Server.Persistence.Migrations
{
    [DbContext(typeof(LivePlayDbContext))]
    [Migration("20240708231419_LivePlayDb_1")]
    partial class LivePlayDb_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.CouponEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("CouponData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinalDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.CreativeQuestEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PictureInfo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("CreativeQuest");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.FeedbackEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte>("Rate")
                        .HasColumnType("smallint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.HotelEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.NewsEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.PermissionEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ReadQuest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CreateQuest"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DeleteQuest"
                        },
                        new
                        {
                            Id = 4,
                            Name = "UpdateQuest"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ReadCoupon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CreateCoupon"
                        },
                        new
                        {
                            Id = 7,
                            Name = "DeleteCoupon"
                        },
                        new
                        {
                            Id = 8,
                            Name = "UpdateCoupon"
                        },
                        new
                        {
                            Id = 9,
                            Name = "UpdateSelf"
                        },
                        new
                        {
                            Id = 10,
                            Name = "DeleteSelf"
                        },
                        new
                        {
                            Id = 11,
                            Name = "GetSelf"
                        });
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.QRQuestEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("QRInfo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestId")
                        .IsUnique();

                    b.ToTable("QRQuest");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.QuestEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionFull")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionMini")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinalDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Reward")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Quest");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.QuestionQuestEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FourthAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RightAnswer")
                        .HasColumnType("integer");

                    b.Property<string>("SecondAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThirdAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestionQuest");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.RoleEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.UserEntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.HotelQuestEntityModel", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.HasKey("HotelId", "QuestId");

                    b.HasIndex("QuestId");

                    b.ToTable("HotelQuest");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.RolePermissionEntityModel", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        });
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.UserCouponEntityModel", b =>
                {
                    b.Property<int>("CouponId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GetDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CouponId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCoupon");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.UserQuestEntityModel", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GetDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("QuestId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuest");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.UserRoleEntityModel", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.CreativeQuestEntityModel", b =>
                {
                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.QuestEntityModel", "Quest")
                        .WithOne("CreativeQuest")
                        .HasForeignKey("LivePlay.Server.Persistence.EntityModels.Base.CreativeQuestEntityModel", "QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.UserEntityModel", "User")
                        .WithMany("CreativeQuests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.FeedbackEntityModel", b =>
                {
                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.UserEntityModel", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.QRQuestEntityModel", b =>
                {
                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.QuestEntityModel", "Quest")
                        .WithOne("QRQuest")
                        .HasForeignKey("LivePlay.Server.Persistence.EntityModels.Base.QRQuestEntityModel", "QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.QuestionQuestEntityModel", b =>
                {
                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.QuestEntityModel", "Quest")
                        .WithMany("QuestionQuests")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.HotelQuestEntityModel", b =>
                {
                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.HotelEntityModel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.QuestEntityModel", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.RolePermissionEntityModel", b =>
                {
                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.PermissionEntityModel", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.RoleEntityModel", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.UserCouponEntityModel", b =>
                {
                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.CouponEntityModel", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.UserEntityModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.UserQuestEntityModel", b =>
                {
                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.QuestEntityModel", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.UserEntityModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.ManyMany.UserRoleEntityModel", b =>
                {
                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.RoleEntityModel", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivePlay.Server.Persistence.EntityModels.Base.UserEntityModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.QuestEntityModel", b =>
                {
                    b.Navigation("CreativeQuest");

                    b.Navigation("QRQuest");

                    b.Navigation("QuestionQuests");
                });

            modelBuilder.Entity("LivePlay.Server.Persistence.EntityModels.Base.UserEntityModel", b =>
                {
                    b.Navigation("CreativeQuests");

                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
